### ISSUE TITLE
Permission problems under Fedora27 with SELinux enabled

### ISSUE THREAD

**Issue by vstoykov** [hyperledger/composer-tools#101]
When I'm following the tutorial:

 - https://hyperledger.github.io/composer/installing/development-tools.html
 - https://hyperledger.github.io/composer/tutorials/developer-tutorial.html

I have problems if SELinux is enabled (it's enabled by default on Fedora). As a workaround I can disable SELinux (`setenforce 0`) temporary during development with composer but this is not good.

I tried to see if changing the mount options in `docker-composer.yml` file by adding `:z` can help with that problem (https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/) and I have mixed success.

When I execute:
```
./startFabric.sh
./createPeerAdminCard.sh
```
now works but after some time my machine become unresponsive and need to reboot.

I'll continue to experiment and see if I can make it work without disabling SELinux.

**Comment by vstoykov** [comment]
What I found is that when I'm sharing `/var/run` of the host for peer0.org1.example.com then my machine became unresponsive. I tried to share only docker.sock in it with `:z` but this command is still failing with permission denied by SELinux:
```
composer network start --card PeerAdmin@hlfv1 --networkAdmin admin --networkAdminEnrollSecret adminpw --archiveFiletutorial-network@0.0.1.bna --file networkadmin.card
```

When I searched more I found more info https://unix.stackexchange.com/questions/386767/selinux-and-docker-allow-access-to-x-unix-socket-in-tmp-x11-unix. It's related to sharing X socket but I think that it is somehow related.

When I execute `ausearch -c 'peer' --raw` there is:
```
type=AVC msg=audit(1518602119.703:775): avc:  denied  { connectto } for  pid=9381 comm="peer" path="/run/docker.sock" scontext=system_u:system_r:container_t:s0:c346,c662 tcontext=system_u:system_r:container_runtime_t:s0 tclass=unix_stream_socket permissive=0
```
and what attract my attention is: 
```
scontext=system_u:system_r:container_t:s0:c346,c662 
tcontext=system_u:system_r:container_runtime_t:s0
```

**Comment by vstoykov** [comment]
From the stackexchange question that I posted above I added `security_opt` to `docker-compose.yml` and now it looks like it is working. Currently the part of my `docker-compose.yml` looks like this:
```
  peer0.org1.example.com:
    ...
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock:z
        - ./:/etc/hyperledger/configtx:z
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/peer/msp:z
        - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users:z
    security_opt:
      - label:type:container_runtime_t
    ...
```

Changes that I've made:

 1. Added `:z` at the end of every volume definition for every service.
 2. Instead of mounting the whole `/var/run` from the host to mount only `docker.sock` socket file
 3. Added `security_opt` section to `peer0.org1.example.com` to set the same label as currently defined by default SELinux policy on Fedora.

Do you want from me to create a Pull Request with these changes?
